// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-diseases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/data/diseases.ts
var symptoms = [
  "Yellow leaves",
  "Brown spots on leaves",
  "Wilting",
  "White powdery coating",
  "Black spots",
  "Curling leaves",
  "Stunted growth",
  "Root rot",
  "Fruit discoloration",
  "Stem lesions",
  "Leaf holes",
  "Mold growth"
];
var diseases = [
  {
    id: "1",
    name: "Late Blight",
    crop: "Tomato / Potato",
    symptoms: ["Brown spots on leaves", "Black spots", "Fruit discoloration"],
    description: "Late blight is caused by the oomycete Phytophthora infestans. It spreads rapidly in cool, moist conditions and can destroy entire fields within days.",
    treatment: [
      "Apply copper-based fungicide immediately",
      "Remove and destroy infected plants",
      "Improve air circulation between plants",
      "Use resistant varieties for next planting"
    ],
    prevention: [
      "Plant resistant varieties",
      "Ensure proper spacing",
      "Avoid overhead irrigation",
      "Rotate crops annually"
    ],
    severity: "high"
  },
  {
    id: "2",
    name: "Powdery Mildew",
    crop: "Wheat / Cucurbits",
    symptoms: ["White powdery coating", "Curling leaves", "Stunted growth"],
    description: "Powdery mildew appears as white powdery spots on leaves and stems. It thrives in warm, dry climates with high humidity.",
    treatment: [
      "Apply sulfur-based fungicide",
      "Use neem oil spray weekly",
      "Remove heavily infected leaves",
      "Increase air circulation"
    ],
    prevention: [
      "Plant in full sunlight",
      "Avoid overcrowding",
      "Water at base of plants",
      "Choose resistant varieties"
    ],
    severity: "medium"
  },
  {
    id: "3",
    name: "Fusarium Wilt",
    crop: "Banana / Tomato",
    symptoms: ["Yellow leaves", "Wilting", "Stunted growth"],
    description: "Fusarium wilt is a soil-borne fungal disease that blocks water-conducting vessels. Lower leaves yellow first, often on one side of the plant.",
    treatment: [
      "No chemical cure \u2014 remove infected plants",
      "Solarize soil before replanting",
      "Use biological control agents (Trichoderma)",
      "Adjust soil pH to 6.5\u20137.0"
    ],
    prevention: [
      "Use disease-free seedlings",
      "Practice crop rotation (3-4 years)",
      "Improve soil drainage",
      "Use resistant varieties"
    ],
    severity: "high"
  },
  {
    id: "4",
    name: "Bacterial Leaf Spot",
    crop: "Pepper / Tomato",
    symptoms: ["Brown spots on leaves", "Leaf holes", "Fruit discoloration"],
    description: "Caused by Xanthomonas bacteria, this disease creates small, dark, water-soaked spots on leaves that may merge and cause defoliation.",
    treatment: [
      "Apply copper hydroxide spray",
      "Remove infected plant debris",
      "Avoid working with wet plants",
      "Use bactericide as preventative"
    ],
    prevention: [
      "Use certified disease-free seeds",
      "Rotate crops every 2-3 years",
      "Avoid overhead watering",
      "Sanitize garden tools"
    ],
    severity: "medium"
  },
  {
    id: "5",
    name: "Root Rot",
    crop: "Various crops",
    symptoms: ["Root rot", "Wilting", "Yellow leaves", "Stunted growth"],
    description: "Root rot is caused by overwatering and poor drainage, leading to fungal growth (Pythium, Phytophthora) that destroys root systems.",
    treatment: [
      "Improve drainage immediately",
      "Reduce watering frequency",
      "Apply fungicide drench to soil",
      "Transplant to fresh, well-draining soil"
    ],
    prevention: [
      "Ensure proper soil drainage",
      "Avoid overwatering",
      "Use raised beds in heavy soils",
      "Add organic matter to improve soil structure"
    ],
    severity: "medium"
  },
  {
    id: "6",
    name: "Downy Mildew",
    crop: "Grapes / Lettuce",
    symptoms: ["Yellow leaves", "Mold growth", "Brown spots on leaves"],
    description: "Downy mildew thrives in cool, wet conditions. Yellow patches appear on upper leaf surfaces with grayish-purple mold underneath.",
    treatment: [
      "Apply mancozeb or metalaxyl fungicide",
      "Remove infected leaves promptly",
      "Improve ventilation in greenhouse",
      "Reduce leaf wetness duration"
    ],
    prevention: [
      "Space plants for air flow",
      "Water in the morning",
      "Use drip irrigation",
      "Apply preventive fungicides in wet seasons"
    ],
    severity: "high"
  }
];

// src/lib/mcp/tools/list-diseases.ts
var list_diseases_default = defineTool({
  name: "list_diseases",
  title: "List crop diseases",
  description: "Return the full CropGuard almanac of crop diseases with symptoms, treatment, prevention, and severity.",
  inputSchema: {
    crop: z.string().optional().describe("Optional case-insensitive substring filter matched against the disease's crop field.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ crop }) => {
    const filtered = crop ? diseases.filter((d) => d.crop.toLowerCase().includes(crop.toLowerCase())) : diseases;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { count: filtered.length, diseases: filtered }
    };
  }
});

// src/lib/mcp/tools/search-by-symptoms.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_by_symptoms_default = defineTool2({
  name: "search_diseases_by_symptoms",
  title: "Diagnose by symptoms",
  description: "Given a list of observed symptoms, return likely crop diseases ranked by how many symptoms match. Use one or more of the supported symptom labels.",
  inputSchema: {
    symptoms: z2.array(z2.string()).min(1).describe(
      `List of observed symptoms. Supported labels: ${symptoms.join(", ")}. Free-form text is matched case-insensitively.`
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ symptoms: input }) => {
    const lower = input.map((s) => s.toLowerCase().trim());
    const scored = diseases.map((d) => {
      const matches = d.symptoms.filter(
        (s) => lower.some((q) => s.toLowerCase().includes(q) || q.includes(s.toLowerCase()))
      );
      return { disease: d, matchCount: matches.length, matchedSymptoms: matches };
    }).filter((r) => r.matchCount > 0).sort((a, b) => b.matchCount - a.matchCount);
    return {
      content: [
        {
          type: "text",
          text: scored.length === 0 ? "No matching diseases found for those symptoms." : JSON.stringify(scored, null, 2)
        }
      ],
      structuredContent: { results: scored }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my CropGuard profile",
  description: "Return the signed-in user's CropGuard profile, including email, full name, login count, and subscription status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("id, email, full_name, login_count, is_subscribed, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bfmjbukolexlnjgnhefw";
var mcp_default = defineMcp({
  name: "cropguard-mcp",
  title: "CropGuard",
  version: "0.1.0",
  instructions: "CropGuard exposes an editorial almanac of crop diseases plus symptom-based diagnosis. Use `list_diseases` to browse the catalog, `search_diseases_by_symptoms` to match observed symptoms to likely diseases, and `get_my_profile` to read the signed-in farmer's account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_diseases_default, search_by_symptoms_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
